### ISSUE TITLE
Назва репозиторію publisher-slack-bot!

### ISSUE THREAD

**Issue by vit-um** [k3ilona/publisher-slack-bot#14]
Пропоную основну нашу репу з застосунком періменовувати на `ilonabot`  або `ibot` 

За правилами розробки на мові го, назва репозиторію має відповідати назві застосунку.  У нас так:
`github.com/k3ilona/publisher-slack-bot`

Доводиться набирати наступну команду кожного разу:
```sh
✗ ./publisher-slack-bot version
v1.0.0
```

**Comment by Andygol** [comment]
Не бачу сенсу хардодити назву `ilonabot`. Початкова назва `publisher-slack-bot` передає призначення боту та є 'self explanatory'.

**Comment by Andygol** [comment]
Або ж назву можна розширити до `ilona-publisher-slack-bot`

**Comment by vit-um** [comment]
Розширяти точно не слід. Назва репозиторію = назві додатку. Набирати в CLI команду `ilona-publisher-slack-bot` - це буде якесь небодобство. Тому пропоную навпаки зробити назву репи біль компактною та без дефісів.

**Comment by vit-um** [comment]
Зариваю дискусію. Наче різні назви у бота та репо поки не заважають процесу.
