### ISSUE TITLE
Заміна gif на посилання на скрінкаст з https://asciinema.org

### ISSUE THREAD

**Issue by Andygol** [k3ilona/publisher-slack-bot#21]
@vit-um 🙏 можеш замінити gif посиланням на скрінкаст з https://asciinema.org?

Мова про цей файл – https://github.com/k3ilona/publisher-slack-bot/blob/main/assets/img/622883.gif

Дякую!

**Comment by vit-um** [comment]
@Andygol мені здається це хибна практика посилатись в документації на хмарний ресурс, який може й не працювати. Тому витарчав час на локальну гіфку.

**Comment by Andygol** [comment]
Гіфки в документації (з власного досвіду) це погано 👎 . Краще вже відео, його хоча б можна зупиняти, перемотувати на потрібний момент. 

asciinema.org існує вже досить давно та справно працює, як варіант можна тримати у себе файл з самим скрінкастом 😏 .

**Comment by vit-um** [comment]
Пропоную хід конем. Хай буде жива гіфка в документації, але у вигляді посилання на збережений запис на asciinema.org. 
Підійде?

**Comment by Andygol** [comment]
Тоді посилання  нижче гіфки додай, будь ласка.

**Comment by vit-um** [comment]
Робив як рекомендовано тут: 
<img width="590" alt="image" src="https://github.com/k3ilona/publisher-slack-bot/assets/74271908/e7fcc90a-9135-4022-a97a-d80056ee14ca">

**Comment by Andygol** [comment]
@vit-um  Не бачу змін 🤷‍♂️

**Comment by vit-um** [comment]
@Andygol Може ти дивився до злиття гілок. Перевірив зміни є, відкриваєься за посиланням стрім на сайті, як ти просив.

**Comment by Andygol** [comment]
Так, дивився до злиття ПР. Зазвичай тікет прив'язується до відповідного ПР і закривається автоматично, коли ПР зливається з основним кодом, а не руками до того як ПР створено 😉
